/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    id("org.jetbrains.kotlin.jvm").version("1.3.21")

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation ("com.squareup.moshi:moshi-adapters:1.5.0")
    implementation ("com.squareup.moshi:moshi-kotlin:1.5.0")
    implementation ("com.opencsv:opencsv:4.0")
}

application {
    // Define the main class for the application.
    mainClassName = "devfest.bim.AppKt"
}
